name: Publish Binaries

on:
  release:
    types: [published]

jobs:
  build:
    name: Publish for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: callscript
            asset_name: callscript-linux-amd64
          - os: windows-latest
            artifact_name: callscript.exe
            asset_name: callscript-windows-amd64
          - os: macos-latest
            artifact_name: callscript
            asset_name: callscript-macos-amd64
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8 pytest coveralls pytest-cov mypy
    - name: Install PyInstaller
      run: |
        python -m pip install pyinstaller
    - name: Build Executable Binary
      run: |
        pyinstaller callscript/cli.py --onefile
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.PAT }}
        file: dist/*
        file_glob: true
        tag: ${{ github.ref }}
        overwrite: true
        asset_name: ${{ matrix.asset_name }}
