name: Publish Binaries

on:
  push:
    tags:
      - '*'
  release:
    types: [published]

jobs:
  build:
    name: Publish binaries
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8 pytest coveralls pytest-cov mypy
    - name: Install PyInstaller
      run: |
        python -m pip install pyinstaller
    - name: Build Executable Binary
      run: |
        pyinstaller check.py --onefile
        ls -a dist
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.PAT }}
        file: dist/*
        file_glob: true
        tag: ${{ github.ref }}
        overwrite: true
